apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rdsbackup.fullname" . }}
  labels:
    {{- include "rdsbackup.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rdsbackup.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "rdsbackup.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "rdsbackup.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "rdsbackup.fullname" . }}-aws
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "rdsbackup.fullname" . }}-aws
                  key: secret_access_key
            - name: ALIBABA_CLOUD_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "rdsbackup.fullname" . }}-alibaba
                  key: access_key_id
            - name: ALIBABA_CLOUD_ACCESS_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "rdsbackup.fullname" . }}-alibaba
                  key: access_key_secret
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "rdsbackup.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 