{{- if .Values.secrets.aws.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rdsbackup.fullname" . }}-aws
  labels:
    {{- include "rdsbackup.labels" . | nindent 4 }}
type: Opaque
data:
  access_key_id: {{ .Values.secrets.aws.access_key_id | b64enc }}
  secret_access_key: {{ .Values.secrets.aws.secret_access_key | b64enc }}
{{- end }}

{{- if .Values.secrets.alibaba.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rdsbackup.fullname" . }}-alibaba
  labels:
    {{- include "rdsbackup.labels" . | nindent 4 }}
type: Opaque
data:
  access_key_id: {{ .Values.secrets.alibaba.access_key_id | b64enc }}
  access_key_secret: {{ .Values.secrets.alibaba.access_key_secret | b64enc }}
{{- end }} 